language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
before_install:
  - sudo apt-get -y install libc-bin
  - npm install -g npm
script:
  - "npm run-script lint"
  - "npm test"
notifications:
  irc: "chat.freenode.net##node-irc"
